version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.0


    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pyproject.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install poetry
          pip install codecov pytest-cov
          poetry install

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "pyproject.lock" }}

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          pytest --cov=fistro tests/
          coverage run -m pytest
          coverage report

    - store_artifacts:
        path: test-reports
        destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
